@startuml CoSimComponent_Initialization

!include ../includes/sequence_theme.puml

participant "System"                 as Caller COLOR_FRAMEWORK
participant "Component\n(Sub Class)" as Sub    COLOR_SUBCLASS
participant "CoSimComponent\n(Base Class)" as Base COLOR_BASECLASS

== Initialization ==

Caller -> Base: **initialize(t0)**
activate Base

Base -> Base: Set initial time

Base -> Sub: **_initialize_component(t0)**
activate Sub
note left: //abstract//\nLoad model, configure solver,\nset initial state
Sub --> Base
deactivate Sub

Base -> Sub: **_update_output_states(t0)**
activate Sub
note left: //abstract//\nWrite internal state\nto output ports
Sub --> Base
deactivate Sub

Base -> Base: _record_outputs(t0)

Base --> Caller
deactivate Base

@enduml
