@startuml CoSimComponent_Construction

!include ../includes/sequence_theme.puml

hide footbox

participant "User Code"              as User COLOR_USER
participant "Component\n(Sub Class)" as Sub  COLOR_SUBCLASS
participant "CoSimComponent\n(Base Class)" as Base COLOR_BASECLASS

== Construction ==

User -> Sub: **comp = Component(name, ...)**
activate Sub

Sub -> Base: super().~_~_init~_~_(name, ...)
activate Base
Base -> Base: Initialize port containers,\nparameters, history recorder
Base --> Sub
deactivate Base

Sub -> Sub: Populate input_specs, output_specs

Sub --> User
deactivate Sub

@enduml
